config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :activities
  put 'move_activity/:id', to: 'activities#move', as: 'move_activity'

  resources :subsectors
  put 'move_subsector/:id', to: 'subsectors#move', as: 'move_subsector'

  resources :sectors
  put 'move_sector/:id', to: 'sectors#move', as: 'move_sector'

  root 'days#show'

  get 'days/:date', to: 'days#show', as: 'week'

  get '/summary/(:date)', to: 'days#summary', as: 'summary'

  put 'fragments/:id', to: 'fragments#update', as: 'fragment'

  devise_for :users, skip: [:sessions],
    controllers: {
      registrations: "users/registrations",
      passwords: "users/passwords",
      confirmations: "users/confirmations",
      sessions: "users/sessions"
    }
  as :user do
    get 'confirm', to: 'users/registrations#confirm'
    get 'signin' => 'users/sessions#new', :as => :new_user_session
    post 'signin' => 'users/sessions#create', :as => :user_session
    delete 'signout' => 'users/sessions#destroy', :as => :destroy_user_session
  end

  get 'patina', to: 'pages#patina', as: 'patina'
  get 'about', to: 'pages#about', as: 'about'
  get 'how_to', to: 'pages#how_to', as: 'how_to'
  get 'hello' => 'pages#hello', :as => :hello

  get 'statistics', to: 'pages#statistics', as: 'statistics'
  get 'statistics/:id', to: 'pages#statistics_sector', as: 'statistic'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :sectors, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  protected

  def confirmation_required?
    false
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  after_action :create_default_sectors, only: :create

  def confirm
  end

  #The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(_resource)
    confirm_path
  end

  def create_default_sectors
    return unless @user.persisted?
    require "#{Rails.root}/db/seed_helpers.rb"
    create_default_sectors_for_user(@user)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/views/users/shared/_links.html.slim
ul class="nav nav-pills"
  - if controller_name != 'sessions'
    li role="presentation"
      = link_to t('.login'), new_session_path(resource_name)

  - if devise_mapping.registerable? && controller_name != 'registrations' && !current_page?(hello_path)
    li role="presentation"
      = link_to t('.signup'), new_registration_path(resource_name)

  - if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
    li role="presentation"
      = link_to t('.forgot_pass'), new_password_path(resource_name)

  - if devise_mapping.confirmable? && controller_name != 'confirmations'
    li role="presentation"
      = link_to t('.miss_confirm_letter'), new_confirmation_path(resource_name)

  - if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
    li role="presentation"
      = link_to t('.miss_unlock_letter'), new_unlock_path(resource_name)

  - if devise_mapping.omniauthable?
    - resource_class.omniauth_providers.each do |provider|
      li role="presentation"
        = link_to t('.signin_omniauth', provider: provider.to_s.titleize), omniauth_authorize_path(resource_name, provider)