config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :activities
  put 'move_activity/:id', to: 'activities#move', as: 'move_activity'

  resources :subsectors
  put 'move_subsector/:id', to: 'subsectors#move', as: 'move_subsector'

  resources :sectors
  put 'move_sector/:id', to: 'sectors#move', as: 'move_sector'

  root 'days#show'

  get 'days/:date', to: 'days#show', as: 'week'

  get '/summary/(:date)', to: 'days#summary', as: 'summary'

  put 'fragments/:id', to: 'fragments#update', as: 'fragment'

  devise_for :users, skip: [:sessions],
    controllers: {
      registrations: "users/registrations",
      passwords: "users/passwords",
      confirmations: "users/confirmations",
      sessions: "users/sessions"
    }
  as :user do
    get 'confirm', to: 'users/registrations#confirm'
    get 'signin' => 'users/sessions#new', :as => :new_user_session
    post 'signin' => 'users/sessions#create', :as => :user_session
    delete 'signout' => 'users/sessions#destroy', :as => :destroy_user_session
  end

  get 'patina', to: 'pages#patina', as: 'patina'
  get 'about', to: 'pages#about', as: 'about'
  get 'how_to', to: 'pages#how_to', as: 'how_to'
  get 'hello' => 'pages#hello', :as => :hello

  get 'statistics', to: 'pages#statistics', as: 'statistics'
  get 'statistics/:id', to: 'pages#statistics_sector', as: 'statistic'

end

app/views/pages/about.html.slim
.container.container_narrow
  .row.description_block
    = render "about/description.#{I18n.locale}"

app/views/pages/hello.html.slim
.container
  .row.registration_form
    h3 = t('links.hello')
    = render "users/registrations/form_new"
  .row.title_block
    = render "about/title"

app/views/pages/how_to.html.slim
.container.container_narrow
  .row.description_block
    = render "about/instruction.#{I18n.locale}"

app/views/pages/patina.html.erb
<div id='patina-container'>
</div>

<style>
  .node {
    font: 11px sans-serif;
  }
  .node_1 {
    font-size: 16px;
  }
  .node_2 {
    font-size: 13px;
  }

  .link {
    fill: none;
    stroke: #ccc;
    stroke-width: 2px;
  }
  .link_1 {
    stroke-width: 4px;
  }
  .link_0 {
    stroke-width: 5px;
  }
</style>


<script type = "text/javascript">
  var PATINA_JSON = <%= raw(render('/pages/patina.json', @json_locals)) %> ;

  show_patina = function() {
    var diameter = 1200;

    var tree = d3.layout.tree()
        .size([360, diameter / 2 - 150])
        .separation(function(a, b) { return (a.parent == b.parent ? 1 : 2) / a.depth; });

    var diagonal = d3.svg.diagonal.radial()
        .projection(function(d) { return [d.y, d.x / 180 * Math.PI]; });

    var svg = d3.select("#patina-container").append("svg")
        .attr("viewBox", "0 0 " + diameter + " " + diameter)
      .append("g")
        .attr("transform", "translate(" + diameter / 2 + "," + diameter / 2 + ")");


    var nodes = tree.nodes(PATINA_JSON),
        links = tree.links(nodes);

    var link = svg.selectAll(".link")
        .data(links)
      .enter().append("path")
        .attr("class", function(d) { return "link link_" + d.source.depth} )
        .attr("d", function(d) {
            if (d.source.depth == 0) d.source.x = d.target.x;
            //d.target.y = round_to_ellipse(d.target);
            //d.target.x = spread_to_width(d.target);
            return diagonal(d);
         })
        .style("stroke", function(d) { return !d.target.color || d.target.color == '#ffffff' ? '#ccc' : d.target.color; });

    var node = svg.selectAll(".node")
        .data(nodes)
      .enter().append("g")
        .attr("class", function(d) { return "node node_" + d.depth} )
        .attr("transform", function(d) { return "rotate(" + (d.x - 90) + ")translate(" + d.y + ")"; })



    node.append("text")
        .attr("dy", function(d) { return d.depth == 3 ? -4 : -8 })
        .attr("text-anchor", function(d) { return d.x < 180 ? "start" : "end"; })
        .attr("transform", function(d) {
          switch (d.depth) {
            case 1:
              translate = 80;
              break;
            case 2:
              translate = 30;
              break;
            default:
              translate = 10;
          }
          translate = d.x < 180 ? -translate : translate
          return d.x < 180  ? "translate(" + translate + ")" : "rotate(180)translate(" + translate + ")";
        })
        .text(function(d) {
          icon = d.icon ? d.icon : ''
          return d.x < 180 ? icon + " " + d.name : d.name + " " + icon;
        });


    d3.select(self.frameElement).style("height", diameter + "px");

    NProgress.done();
  };

  function round_to_ellipse(d) {
    //return d.y - 15 * Math.pow(d.depth, 2) * Math.abs(1/Math.cos(((d.x+45)%90-45)/180*Math.PI));
    return d.y - 20 * Math.pow(d.depth, 2) * Math.abs(Math.cos((d.x/180)*Math.PI))
  }

  function spread_to_width(d) {
    var offset = 15 * Math.abs(Math.cos((d.x/180)*Math.PI))
    offset = (d.x <= 90 || d.x > 180 && d.x <= 270) ? + offset : - offset;
    return d.x + offset;
  }

  var js = document.createElement("script");
  js.type = "text/javascript";
  js.src = "//d3js.org/d3.v3.min.js";
  js.onreadystatechange = function () {
    if (this.readyState == 'complete') show_patina;
  }
  js.onload = show_patina;
  document.body.appendChild(js);

</script>

app/views/pages/statistics.html.slim
.container
  .row
    h4.text-center = t('.fragments_by_sectors')
    table.table.table-hover
      tr
        th = t('.sectors')
        th = t('.by_month')
        th = t('.by_epoch')
        th = t('.by_all')
      - @sectors.each do |sector|
        tr
          th = link_to sector.name, statistic_path(sector.id)
          td = @fragments_month[sector.id].to_i
          td = @fragments_epoch[sector.id].to_i
          td = @fragments_total[sector.id].to_i

      tr
        th = t('.total')
        td = @fragments_month.values.sum.to_i
        td = @fragments_epoch.values.sum.to_i
        td = @fragments_total.values.sum.to_i

  .row
    h4.text-center = t('.activity_for_month')
    #statistics-chart-container
      javascript:
        window.ACTIVITY_JSON = #{render('/pages/activity.json').html_safe};
        window.I18n = #{I18n.backend.send(:translations)[I18n.locale][:frontend].to_json.html_safe} ;

  .row
    h4.text-center = t('.popular_sectors') + '(' + t("languages.#{I18n.locale}") + ')'
    table.table.table-hover
      tr
        th = t('.sectors')
        th = t('.users_count')
      - @popular_sectors.each do |name, count|
        tr
          th = name
          td = count

app/views/pages/statistics_sector.html.slim
.container
  .row
    h4.text-center = t('.fragments_by_sector', sector: @sector.name)
    table.table.table-hover.table-condensed
      tr
        th = t('.activities')
        th = t('.by_month')
        th = t('.by_epoch')
        th = t('.by_all')

      - @subsectors.each do |subsector|
        tr.active
          td colspan='4'
            = subsector.name
        - @activities_grouped[subsector.id].each do |id, activity|
          tr
            th = activity.name
            td = @fragments_month[activity.id].to_i
            td = @fragments_epoch[activity.id].to_i
            td = @fragments_total[activity.id].to_i

    = link_to t('.go_back'), statistics_path