config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :activities
  put 'move_activity/:id', to: 'activities#move', as: 'move_activity'

  resources :subsectors
  put 'move_subsector/:id', to: 'subsectors#move', as: 'move_subsector'

  resources :sectors
  put 'move_sector/:id', to: 'sectors#move', as: 'move_sector'

  root 'days#show'

  get 'days/:date', to: 'days#show', as: 'week'

  get '/summary/(:date)', to: 'days#summary', as: 'summary'

  put 'fragments/:id', to: 'fragments#update', as: 'fragment'

  devise_for :users, skip: [:sessions],
    controllers: {
      registrations: "users/registrations",
      passwords: "users/passwords",
      confirmations: "users/confirmations",
      sessions: "users/sessions"
    }
  as :user do
    get 'confirm', to: 'users/registrations#confirm'
    get 'signin' => 'users/sessions#new', :as => :new_user_session
    post 'signin' => 'users/sessions#create', :as => :user_session
    delete 'signout' => 'users/sessions#destroy', :as => :destroy_user_session
  end

  get 'patina', to: 'pages#patina', as: 'patina'
  get 'about', to: 'pages#about', as: 'about'
  get 'how_to', to: 'pages#how_to', as: 'how_to'
  get 'hello' => 'pages#hello', :as => :hello

  get 'statistics', to: 'pages#statistics', as: 'statistics'
  get 'statistics/:id', to: 'pages#statistics_sector', as: 'statistic'

end

app/views/layouts/_alerts.html.slim
div id="flash"
  = growlyflash_static_notices

app/views/layouts/_footer.html.slim
#footer
  .container
    .bottom-nav
      = link_to t("links.home"), "http://evopatina.space/"
      = ' | '
      = link_to t("links.feedback"), 'mailto:admin@evopatina.space'

    .sign = t(".sign")

app/views/layouts/_google_analytics.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69060746-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_navbar.html.slim
nav class="navbar navbar-default"
  div class="container-fluid"
    /! Brand and toggle get grouped for better mobile display
    div class="navbar-header"
      button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        span class="sr-only" Toggle navigation
        span class="icon-bar"
        span class="icon-bar"
        span class="icon-bar"

      a class="navbar-brand" href="http://evopatina.herokuapp.com/"
        span class='glyphicon glyphicon-tree-conifer'

    /! Collect the nav links, forms, and other content for toggling
    div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"

      - if user_signed_in?
        ul class="nav navbar-nav"
          = nav_link t("links.summary"), summary_path

        ul class="nav navbar-nav"
          = nav_link t("links.patina"), patina_path

        ul class="nav navbar-nav"
          = nav_link t("links.statistics"), statistics_path

      ul class="nav navbar-nav"
        = nav_link t("links.about"), about_path

      ul class="nav navbar-nav"
        = nav_link t("links.instruction"), how_to_path

      ul class="nav navbar-nav navbar-right"
        - if user_signed_in?
          li class="dropdown"
            a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
              = gliph('user')
              span id="user_name" = current_user.email
              span class="caret"
            ul class="dropdown-menu"
              li = link_to gliph('cog') + t('.edit_profile'), edit_user_registration_path, :class => 'navbar-link'
              li role="separator" class="divider"
              li = link_to gliph('log-out') + t('.logout'), destroy_user_session_path, method: :delete, :class => 'navbar-link'
        - else
          li = link_to gliph('log-in') + t('.login'), new_user_session_path, :class => 'navbar-link'

      ul class="nav navbar-nav navbar-right"
        li class="dropdown"
          a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
            = t("languages.#{I18n.locale}")
            span class="caret"

          ul class="dropdown-menu" role="menu"
            - menu_langs.each do |lang|
              li
                = link_to t("languages.#{lang}"), "?locale=#{lang}"

app/views/layouts/application.html.slim
doctype html
html
  head
    title Evopatina
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'print', media: 'print'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    meta name="viewport" content="width=device-width, initial-scale=1"
    = csrf_meta_tags
  body class= controller.controller_name

    = render '/layouts/navbar'

    = render '/layouts/alerts'

    = yield

    = render '/layouts/footer'